#!/usr/bin/env python3
"""
Converts an ASCII-art text file (UTF-8) into a C header for neofetch.

    python3 build_scripts/generate_ascii_art.py theory/ascii_art.txt src/kernel/shell/ascii_art.h

- the characters are converted to code page 437 (the VGA font): the shade
  blocks ░ ▒ ▓ █ become 0xB0 0xB1 0xB2 0xDB
- empty rows at the top/bottom and the common left margin are removed
- the screen has 25 rows and the prompt needs one: if the drawing is taller
  than MAX_ROWS, one row of each pair of identical consecutive rows is removed
"""
import sys

MAX_ROWS = 24

def main():
    if len(sys.argv) != 3:
        print(__doc__)
        sys.exit(1)

    with open(sys.argv[1], encoding='utf-8') as f:
        rows = [line.rstrip('\n').rstrip() for line in f]

    while rows and not rows[0].strip():
        rows.pop(0)
    while rows and not rows[-1].strip():
        rows.pop()

    margin = min(len(r) - len(r.lstrip(' ')) for r in rows if r.strip())
    rows = [r[margin:] for r in rows]

    i = 0
    while len(rows) > MAX_ROWS and i < len(rows) - 1:
        if rows[i] == rows[i + 1]:
            del rows[i]
        else:
            i += 1
    if len(rows) > MAX_ROWS:
        print(f'warning: the drawing has {len(rows)} rows, only {MAX_ROWS} fit with the prompt')

    width = max(len(r) for r in rows)
    out = []
    out.append('// !!! THIS FILE IS AUTOGENERATED by build_scripts/generate_ascii_art.py !!!')
    out.append(f'// source: {sys.argv[1]}')
    out.append('#pragma once')
    out.append('')
    out.append(f'#define ASCII_ART_WIDTH     {width}')
    out.append(f'#define ASCII_ART_HEIGHT    {len(rows)}')
    out.append('')
    out.append('static const char* const g_AsciiArt[ASCII_ART_HEIGHT] = {')
    for r in rows:
        data = r.encode('cp437', errors='replace')
        out.append('    "' + ''.join(f'\\x{b:02x}' for b in data) + '",')
    out.append('};')
    out.append('')

    with open(sys.argv[2], 'w') as f:
        f.write('\n'.join(out))
    print(f'{sys.argv[2]}: {len(rows)} rows x {width} columns')

if __name__ == '__main__':
    main()
